---
# 
# Configuration for Shinken WebUI
# 

# [ Product ]
# product
#   Name of your Business Unit, of the product for which one that instance
#   is dedicated for, whatever you want. It is a free text.
product: MyShinken

# [ Authentication ]
# auth_method
#   Design of the password to use
#   Availbale methods are: basic (List of users), ldap (Active directory)
auth_method: basic
# auth_list
#   List of users when auth_method = basic
#   Key is username, value is password (digest)
auth_list:
  demo: demo
# auth_digest
#   Compute password with the digest method specified
#   See OpenSSL dgst command for further details
#   Set none for clear password
auth_digest: none
# ldap

# [ Shinken ]
# livestatus
#   Configuration to bind Livestatus
livestatus:
  host: localhost
  port: 50000

# [ Bookmarks ]
# bookrmarks
#   Table of predifined bookmarks shared with all users.
bookmarks:
  - name: Double Trouble
    rules:
      - bi>=4
      - state>=1

...
